import { Redis } from '@upstash/redis';

const redis = Redis.fromEnv();

const PRESEED = [
  { slug: 'ash-fure', name: 'Ash Fure', setday: 'Saturday', settime: '10:00 PM', stage: 'The Inn', checkday: 'Friday', checktime: '12:00 PM', checkstage: 'The Inn', arrDay: 'Friday · Jun 13', arrTime: '12:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Self-driving. 2 meal tokens.' },
  { slug: 'ayanna-heaven', name: 'Ayanna Heaven', setday: 'Saturday', settime: '3:00 PM', stage: 'Open Air', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Saturday · Jun 14', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '1 meal token + 1 Thursday token.' },
  { slug: 'badsista', name: 'Badsista', setday: 'Friday', settime: '2:30 AM', stage: 'The Inn', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'No form response received yet.' },
  { slug: 'black-decelerant', name: 'Black Decelerant', setday: 'Sunday', settime: '1:20 AM', stage: 'Open Air', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '9:00 AM', arrTransport: 'Car pickup from Newark EWR', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Car to Newark EWR', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Omari Jazz + Khari Lucas. Airport pickup Thu. 2 tokens + 2 Thu tokens.' },
  { slug: 'breadwoman', name: 'Breadwoman', setday: 'Saturday', settime: '8:00 PM', stage: 'The Outside Inn', checkday: 'Saturday', checktime: '2:30 PM', checkstage: 'The Outside Inn', rainStage: 'The Inn', rainNote: 'Celiac warning — moved inside to The Inn', arrDay: '', arrTime: '', arrTransport: '', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Car to Newark EWR', tokens: '3', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Anna Homler, Katya Urban, Steven Warwick. Flight AS638 in, AS287 out. Celiac allergy warning if moved inside.' },
  { slug: 'pavel-milyakov', name: 'Buttechno / Pavel Milyakov', setday: 'Thursday', settime: '10:30 PM', stage: 'Open Air', checkday: 'Thursday', checktime: '4:00 PM', checkstage: 'Open Air', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Saturday · Jun 14', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Arriving JFK. Shuttle both ways. German phone: +4917637419748.' },
  { slug: 'c-lavender', name: 'C. Lavender', setday: 'Friday', settime: '5:15 AM', stage: 'Open Air', checkday: 'Saturday', checktime: '4:30 AM', checkstage: 'Open Air', arrDay: 'Saturday · Jun 14', arrTime: '12:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Saturday · Jun 14', depTime: '6:00 PM', depTransport: 'Self-driving / own car', tokens: '2', lodging: 'none', langs: ['en'], defaultLang: 'en', notes: 'Lavender Suarez. Self-driving, same-day arrival and departure. 2 tokens.' },
  { slug: 'choke-hole', name: 'Choke Hole', setday: 'Saturday', settime: '9:00 PM', stage: 'Hammock Grove', checkday: 'Saturday', checktime: '12:30 PM', checkstage: 'Hammock Grove', rainStage: 'The Barn', rainNote: 'Rain plan: moved to The Barn', arrDay: 'Saturday · Jun 14', arrTime: '12:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '6', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '6 performers: Ellery Neon, Jassy, Hannah Joffrey, Sam Springston, Caratoes, Boy Radio. 6 tokens + 6 Thu tokens.' },
  { slug: 'dj-bobby-beethoven', name: 'DJ Bobby Beethoven', setday: 'Sunday', settime: '3:00 AM', stage: 'The Inn', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '2 meal tokens. No travel info submitted.' },
  { slug: 'dj-manny', name: 'DJ Manny', setday: 'Saturday', settime: '11:00 PM', stage: 'The Inn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '1 meal token + 1 Thu token. Shuttle both ways.' },
  { slug: 'dj-ojo', name: 'DJ ojo', setday: 'Friday', settime: '11:30 PM', stage: 'The Inn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Joe Carver. UK phone: +447469960305. Shuttle both ways.' },
  { slug: 'doula', name: 'Doula', setday: 'Friday', settime: '11:00 PM', stage: 'The Barn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Shuttle both ways. No token count yet.' },
  { slug: 'earthen-sea', name: 'Earthen Sea', setday: 'Sunday', settime: '2:40 AM', stage: 'Open Air', checkday: 'Saturday', checktime: '11:30 AM', checkstage: 'Open Air', arrDay: 'Saturday · Jun 14', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Friday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Jacob Long. Shuttle both ways.' },
  { slug: 'eden-aurelius', name: 'Eden Aurelius', setday: 'Friday', settime: '9:00 PM', stage: 'The Barn', checkday: 'Friday', checktime: '3:00 PM', checkstage: 'The Barn', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '1 meal token + 1 Thu token.' },
  { slug: 'elori-saxl-henry-solomon', name: 'Elori Saxl & Henry Solomon', setday: 'Sunday', settime: '12:00 AM', stage: 'Open Air', checkday: 'Saturday', checktime: '11:00 PM', checkstage: 'Open Air', arrDay: 'Saturday · Jun 14', arrTime: '12:00 PM', arrTransport: 'Car pickup from Newark EWR', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Car to Newark EWR', tokens: '4', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Elori self-driving, Henry may need airport transport from NYC. 4 tokens.' },
  { slug: 'everything-upful', name: 'Everything Upful', setday: 'Saturday', settime: '4:00 PM', stage: 'Open Air', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '4', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Gavsborg, Groundsound, Kat7 & Tóke. 4 tokens + 4 Thu tokens.' },
  { slug: 'fried-platano', name: 'Fried Platano', setday: 'Sunday', settime: '12:00 AM', stage: 'The Barn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Elvin Tavarez. Self-driving. 1 token.' },
  { slug: 'fujiiiiiiiiiiiita', name: 'FujiIIIIIIIIIIIta', setday: 'Saturday', settime: '7:00 PM', stage: 'The Inn', checkday: 'Saturday', checktime: '5:00 PM', checkstage: 'The Inn', arrDay: 'Saturday · Jun 14', arrTime: '12:00 PM', arrTransport: 'Car pickup from Newark EWR', depDay: 'Sunday · Jun 15', depTime: '2:00 PM', depTransport: 'Car to Newark EWR', tokens: '2', lodging: 'hotel', langs: ['en', 'ja'], defaultLang: 'ja', notes: 'Yosuke Fujita. Flight AC7665 arriving Newark 12:06pm Jun 13. Japanese speaker.' },
  { slug: 'gyrofield', name: 'gyrofield', setday: 'Sunday', settime: '1:00 AM', stage: 'The Inn', checkday: '', checktime: '', arrDay: 'Friday · Jun 13', arrTime: '3:00 PM', arrTransport: 'Car pickup from Newark EWR', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Car to Newark EWR', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Kiana Li. Flights UA71/UA70. UK phone: +447311449832.' },
  { slug: 'hesaitix', name: 'Hesaitix', setday: 'Friday', settime: '10:00 PM', stage: 'The Barn', checkday: 'Friday', checktime: '2:00 PM', checkstage: 'The Barn', arrDay: 'Friday · Jun 13', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Friday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'James Whipple. Shuttle both ways. 2 tokens.' },
  { slug: 'honey-pluton', name: 'Honey Pluton & Spike Einbinder', setday: 'Saturday', settime: '1:30 PM', stage: 'Lakeside Amphitheater', checkday: 'Saturday', checktime: '11:30 AM', checkstage: 'Lakeside Amphitheater', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Honey: 206-778-7459 / Spike: 310-709-8855. Self-driving. 2 tokens + 2 Thu tokens.' },
  { slug: 'in-the-mela', name: 'In The Mela: Baalti & Sayoko', setday: 'Saturday', settime: '2:30 PM', stage: 'The Barn', checkday: 'Saturday', checktime: '9:00 AM', checkstage: 'The Barn', arrDay: 'Thursday · Jun 12', arrTime: '9:00 AM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '3', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Baalti (Mihir Chauhan, Jaiveer Singh) & Sayoko. On site early in the week. 3 tokens + 3 Thu tokens.' },
  { slug: 'isabella-koen', name: 'Isabella Koen', setday: 'Friday', settime: '1:00 AM', stage: 'The Barn', checkday: 'Friday', checktime: '1:00 PM', checkstage: 'The Barn', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Self-driving. 2 tokens.' },
  { slug: 'joao-lagrima', name: 'João Lágrima de Ouro', setday: 'Sunday', settime: '4:00 AM', stage: 'The Barn', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '', lodging: 'hotel', langs: ['en', 'pt'], defaultLang: 'pt', notes: 'No form response yet. Portuguese speaker.' },
  { slug: 'joselo', name: 'Joselo', setday: 'Saturday', settime: '10:00 PM', stage: 'The Barn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Sunday · Jun 15', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '1', lodging: 'hotel', langs: ['en', 'es'], defaultLang: 'es', notes: '1 token + 1 Thu token. Shuttle both ways.' },
  { slug: 'juliana-huxtable', name: 'Juliana Huxtable', setday: 'Sunday', settime: '5:00 AM', stage: 'The Inn', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '4', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '4 tokens. No travel info submitted.' },
  { slug: 'ka-baird', name: 'Ka Baird', setday: 'Friday', settime: '8:30 PM', stage: 'The Inn', checkday: 'Friday', checktime: '7:00 PM', checkstage: 'The Inn', arrDay: 'Friday · Jun 13', arrTime: '12:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Self-driving. 1 token + 1 Thu token.' },
  { slug: 'keiyaa', name: 'keiyaA', setday: 'Thursday', settime: '9:00 PM', stage: 'The Inn', checkday: 'Thursday', checktime: '8:00 PM', checkstage: 'The Inn', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Chakeiya Richmond, Harlem Farr, Stevee Bartashev. No travel info submitted.' },
  { slug: 'kiernan-laveaux', name: 'Kiernan Laveaux', setday: 'Friday', settime: '3:00 PM', stage: 'The Lake', checkday: 'Friday', checktime: '12:30 PM', checkstage: 'The Lake', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: '1 token + 1 Thu token. Self-driving.' },
  { slug: 'livwutang', name: 'livwutang', setday: 'Friday', settime: '9:30 PM', stage: 'The Inn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Liv Klutse. Self-driving. 1 token + 1 Thu token.' },
  { slug: 'mad-professor', name: 'Mad Professor', setday: 'Friday', settime: '12:30 AM', stage: 'The Inn', checkday: 'Friday', checktime: '5:30 PM', checkstage: 'The Inn', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Saturday · Jun 14', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Neil Fraser. UK phone: +447785326048. Flight TBC.' },
  { slug: 'max-in-the-world', name: 'Max in the World & Kroba', setday: 'Saturday', settime: '12:00 PM', stage: 'The Lake', checkday: 'Saturday', checktime: '10:00 AM', checkstage: 'The Lake', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Maxwell Reid (516-987-1651) & Zachary Koeber (845-661-3056). Self-driving.' },
  { slug: 'monica-mirabile', name: 'Monica Mirabile & ADR', setday: 'Friday', settime: '12:00 AM', stage: 'Open Air', checkday: 'Friday', checktime: '6:00 PM', checkstage: 'Open Air', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '5', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Monica Mirabile, Sigrid Lauren, TaraJo Tashna, Kinlaw. 5 tokens + 5 Thu tokens.' },
  { slug: 'motherboard', name: 'MOTHERBOARD', setday: 'Thursday', settime: '8:00 PM', stage: 'The Inn', checkday: 'Thursday', checktime: '6:30 PM', checkstage: 'The Inn', arrDay: 'Thursday · Jun 12', arrTime: '1:00 PM', arrTransport: 'Shuttle from Nowadays — Thursday 1PM', depDay: 'Friday · Jun 13', depTime: '12:30 PM', depTransport: 'Shuttle from Nowadays — Sunday 12:30PM', tokens: '2', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Kyle Kidd. Shuttle in, out Fri. 2 tokens.' },
  { slug: 'multicast-dynamics', name: 'Multicast Dynamics', setday: 'Friday', settime: '1:00 AM', stage: 'Open Air', checkday: 'Friday', checktime: '1:00 PM', checkstage: 'Open Air', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Samuel. Finland phone: +358404782520. Flight AY0015. 1 token + 1 Thu token.' },
  { slug: 'sevyn-love', name: 'Sevyn Love', setday: 'Sunday', settime: '2:00 AM', stage: 'The Barn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Self-driving. 1 token + 1 Thu token.' },
  { slug: 'toki-fuko', name: 'Toki Fuko', setday: 'Sunday', settime: '4:00 AM', stage: 'Open Air', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '9:00 AM', arrTransport: 'Car pickup from Newark EWR', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Car to Newark EWR', tokens: '3', lodging: 'hotel', langs: ['en', 'ru'], defaultLang: 'ru', notes: 'Russian phone: +79058558772. Flight TBC. 3 tokens + 1 Thu token.' },
  { slug: 'zi', name: 'Zi!', setday: 'Friday', settime: '3:00 AM', stage: 'The Barn', checkday: '', checktime: '', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '1', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Ziryab El Hihi. Montreal: +14384092962. 1 token + 1 Thu token.' },
  { slug: 'sonic-mobile-upsammy', name: 'Sonic Mobile: Upsammy', setday: 'Thursday', settime: '12:00 PM', stage: 'Hammock Grove', checkday: '', checktime: '', arrDay: '', arrTime: '', arrTransport: '', depDay: '', depTime: '', depTransport: '', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'All-day sonic mobile Thursday–Sunday.' },
  { slug: 'workshop-alex-tatarsky', name: 'Workshop: Alex Tatarsky', setday: 'Friday', settime: '4:30 PM', stage: 'The Outside Inn', checkday: 'Friday', checktime: '4:00 PM', checkstage: 'The Outside Inn', arrDay: 'Thursday · Jun 12', arrTime: '6:00 PM', arrTransport: 'Self-driving / own car', depDay: 'Sunday · Jun 15', depTime: '12:00 PM', depTransport: 'Self-driving / own car', tokens: '', lodging: 'hotel', langs: ['en'], defaultLang: 'en', notes: 'Alex Tatarsky + Shane Riley. Self-driving.' },
];

export default async function handler(req, res) {
  // Simple auth check — only allow if secret param matches
  if (req.query.secret !== process.env.SEED_SECRET && req.query.secret !== 'dripping2026seed') {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    let count = 0;
    for (const artist of PRESEED) {
      const { slug, ...data } = artist;
      await redis.set(`dripping26_${slug}`, JSON.stringify(data));
      count++;
    }
    return res.status(200).json({ ok: true, seeded: count });
  } catch (err) {
    console.error('Seed error:', err.message);
    return res.status(500).json({ error: err.message });
  }
}
